######################################################

      ##         ##  ##########       ########
      ####       ##  ##        ##   ##        ##
      ##  ##     ##  ##        ##  ##
      ##    ##   ##  ##########    ##
      ##     ##  ##  ##            ##
      ##       ####  ##             ##        ##
      ##         ##  ##               ########

######################################################

name: NPC
version: 1.0.0
author: Weapie
api-version: "1.13"
depend: [ProtocolLib]
main: de.weapie.npc.Main